import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:lume_design_system/theme/lume_theme.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

// Generated by build_runner — re-run `dart run build_runner build` after
// adding new @widgetbook.UseCase annotations.
import 'widgetbook.app.directories.g.dart';

@widgetbook.App()
class LumeWidgetbook extends StatelessWidget {
  const LumeWidgetbook({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(name: 'Light', data: lumeLightTheme()),
            WidgetbookTheme(name: 'Dark', data: lumeDarkTheme()),
          ],
        ),
        ViewportAddon([
          IosViewports.iPhone13,
          IosViewports.iPhone13ProMax,
          IosViewports.iPhone13Mini,
          IosViewports.iPhoneSE,
          AndroidViewports.samsungGalaxyS20,
          AndroidViewports.samsungGalaxyA50,
        ]),
        TextScaleAddon(min: 0.8, max: 2.0),
        LocalizationAddon(
          locales: [const Locale('pt', 'BR'), const Locale('en')],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
        ),
      ],
    );
  }
}
