// Mocks generated by Mockito from annotations
// in lume/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:lume/core/auth/auth_token_provider.dart' as _i11;
import 'package:lume/core/network/api_client.dart' as _i7;
import 'package:lume/core/network/api_response.dart' as _i8;
import 'package:lume/core/network/http_method.dart' as _i9;
import 'package:lume/layers/data/datasource/category_preference_data_source.dart'
    as _i15;
import 'package:lume/layers/data/datasource/game_data_source.dart' as _i13;
import 'package:lume/layers/data/datasource/profile_data_source.dart' as _i14;
import 'package:lume/layers/data/datasource/trail_data_source.dart' as _i12;
import 'package:lume/layers/data/models/category_data.dart' as _i6;
import 'package:lume/layers/data/models/game_data.dart' as _i4;
import 'package:lume/layers/data/models/profile_data.dart' as _i5;
import 'package:lume/layers/data/models/trail_progress_data.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrailBootstrapData_1 extends _i1.SmartFake
    implements _i3.TrailBootstrapData {
  _FakeTrailBootstrapData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrailProgressData_2 extends _i1.SmartFake
    implements _i3.TrailProgressData {
  _FakeTrailProgressData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevelProgressData_3 extends _i1.SmartFake
    implements _i3.LevelProgressData {
  _FakeLevelProgressData_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePairProgressData_4 extends _i1.SmartFake
    implements _i3.PairProgressData {
  _FakePairProgressData_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubmoduleGamesData_5 extends _i1.SmartFake
    implements _i4.SubmoduleGamesData {
  _FakeSubmoduleGamesData_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileData_6 extends _i1.SmartFake implements _i5.ProfileData {
  _FakeProfileData_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryPreferencesData_7 extends _i1.SmartFake
    implements _i6.CategoryPreferencesData {
  _FakeCategoryPreferencesData_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  @override
  _i2.Future<_i8.ApiResponse<T>> request<T>({
    required _i9.HttpMethod? method,
    required String? endpoint,
    Map<String, Object?>? queryParameters,
    Map<String, String>? headers,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #method: method,
              #endpoint: endpoint,
              #queryParameters: queryParameters,
              #headers: headers,
              #body: body,
            }),
            returnValue: _i2.Future<_i8.ApiResponse<T>>.value(
              _i10.dummyValue<_i8.ApiResponse<T>>(
                this,
                Invocation.method(#request, [], {
                  #method: method,
                  #endpoint: endpoint,
                  #queryParameters: queryParameters,
                  #headers: headers,
                  #body: body,
                }),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i8.ApiResponse<T>>.value(
              _i10.dummyValue<_i8.ApiResponse<T>>(
                this,
                Invocation.method(#request, [], {
                  #method: method,
                  #endpoint: endpoint,
                  #queryParameters: queryParameters,
                  #headers: headers,
                  #body: body,
                }),
              ),
            ),
          )
          as _i2.Future<_i8.ApiResponse<T>>);

  @override
  _i2.Future<T> get<T>({
    required String? endpoint,
    Map<String, Object?>? queryParameters = const {},
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #endpoint: endpoint,
              #queryParameters: queryParameters,
              #headers: headers,
            }),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#get, [], {
                      #endpoint: endpoint,
                      #queryParameters: queryParameters,
                      #headers: headers,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#get, [], {
                    #endpoint: endpoint,
                    #queryParameters: queryParameters,
                    #headers: headers,
                  }),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#get, [], {
                      #endpoint: endpoint,
                      #queryParameters: queryParameters,
                      #headers: headers,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#get, [], {
                    #endpoint: endpoint,
                    #queryParameters: queryParameters,
                    #headers: headers,
                  }),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> post<T>({
    required String? endpoint,
    Object? body,
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [], {
              #endpoint: endpoint,
              #body: body,
              #headers: headers,
            }),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#post, [], {
                      #endpoint: endpoint,
                      #body: body,
                      #headers: headers,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#post, [], {
                    #endpoint: endpoint,
                    #body: body,
                    #headers: headers,
                  }),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#post, [], {
                      #endpoint: endpoint,
                      #body: body,
                      #headers: headers,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#post, [], {
                    #endpoint: endpoint,
                    #body: body,
                    #headers: headers,
                  }),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> rpc<T>(
    String? name, {
    Object? params,
    Map<String, String>? headers = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rpc,
              [name],
              {#params: params, #headers: headers},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #rpc,
                      [name],
                      {#params: params, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #rpc,
                    [name],
                    {#params: params, #headers: headers},
                  ),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #rpc,
                      [name],
                      {#params: params, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #rpc,
                    [name],
                    {#params: params, #headers: headers},
                  ),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [AuthTokenProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenProvider extends _i1.Mock
    implements _i11.AuthTokenProvider {}

/// A class which mocks [TrailDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrailDataSource extends _i1.Mock implements _i12.TrailDataSource {
  @override
  _i2.Future<_i3.TrailBootstrapData> fetchBootstrap() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBootstrap, []),
            returnValue: _i2.Future<_i3.TrailBootstrapData>.value(
              _FakeTrailBootstrapData_1(
                this,
                Invocation.method(#fetchBootstrap, []),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i3.TrailBootstrapData>.value(
              _FakeTrailBootstrapData_1(
                this,
                Invocation.method(#fetchBootstrap, []),
              ),
            ),
          )
          as _i2.Future<_i3.TrailBootstrapData>);

  @override
  _i2.Future<_i3.TrailProgressData> fetchProgress() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProgress, []),
            returnValue: _i2.Future<_i3.TrailProgressData>.value(
              _FakeTrailProgressData_2(
                this,
                Invocation.method(#fetchProgress, []),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i3.TrailProgressData>.value(
              _FakeTrailProgressData_2(
                this,
                Invocation.method(#fetchProgress, []),
              ),
            ),
          )
          as _i2.Future<_i3.TrailProgressData>);

  @override
  _i2.Future<List<_i4.GameTrailData>> fetchGameTrails() =>
      (super.noSuchMethod(
            Invocation.method(#fetchGameTrails, []),
            returnValue: _i2.Future<List<_i4.GameTrailData>>.value(
              <_i4.GameTrailData>[],
            ),
            returnValueForMissingStub:
                _i2.Future<List<_i4.GameTrailData>>.value(
                  <_i4.GameTrailData>[],
                ),
          )
          as _i2.Future<List<_i4.GameTrailData>>);

  @override
  _i2.Future<_i3.LevelProgressData> saveLevelQuiz({
    required int? levelId,
    required num? score,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveLevelQuiz, [], {
              #levelId: levelId,
              #score: score,
            }),
            returnValue: _i2.Future<_i3.LevelProgressData>.value(
              _FakeLevelProgressData_3(
                this,
                Invocation.method(#saveLevelQuiz, [], {
                  #levelId: levelId,
                  #score: score,
                }),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i3.LevelProgressData>.value(
              _FakeLevelProgressData_3(
                this,
                Invocation.method(#saveLevelQuiz, [], {
                  #levelId: levelId,
                  #score: score,
                }),
              ),
            ),
          )
          as _i2.Future<_i3.LevelProgressData>);

  @override
  _i2.Future<_i3.PairProgressData> savePairProgress({
    required int? pairId,
    required int? scorePct,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePairProgress, [], {
              #pairId: pairId,
              #scorePct: scorePct,
            }),
            returnValue: _i2.Future<_i3.PairProgressData>.value(
              _FakePairProgressData_4(
                this,
                Invocation.method(#savePairProgress, [], {
                  #pairId: pairId,
                  #scorePct: scorePct,
                }),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i3.PairProgressData>.value(
              _FakePairProgressData_4(
                this,
                Invocation.method(#savePairProgress, [], {
                  #pairId: pairId,
                  #scorePct: scorePct,
                }),
              ),
            ),
          )
          as _i2.Future<_i3.PairProgressData>);
}

/// A class which mocks [GameDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameDataSource extends _i1.Mock implements _i13.GameDataSource {
  @override
  _i2.Future<_i4.SubmoduleGamesData> fetchSubmoduleGames({
    required int? submoduleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubmoduleGames, [], {
              #submoduleId: submoduleId,
            }),
            returnValue: _i2.Future<_i4.SubmoduleGamesData>.value(
              _FakeSubmoduleGamesData_5(
                this,
                Invocation.method(#fetchSubmoduleGames, [], {
                  #submoduleId: submoduleId,
                }),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i4.SubmoduleGamesData>.value(
              _FakeSubmoduleGamesData_5(
                this,
                Invocation.method(#fetchSubmoduleGames, [], {
                  #submoduleId: submoduleId,
                }),
              ),
            ),
          )
          as _i2.Future<_i4.SubmoduleGamesData>);
}

/// A class which mocks [ProfileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDataSource extends _i1.Mock implements _i14.ProfileDataSource {
  @override
  _i2.Future<_i5.ProfileData> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i2.Future<_i5.ProfileData>.value(
              _FakeProfileData_6(this, Invocation.method(#fetchProfile, [])),
            ),
            returnValueForMissingStub: _i2.Future<_i5.ProfileData>.value(
              _FakeProfileData_6(this, Invocation.method(#fetchProfile, [])),
            ),
          )
          as _i2.Future<_i5.ProfileData>);
}

/// A class which mocks [CategoryPreferenceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryPreferenceDataSource extends _i1.Mock
    implements _i15.CategoryPreferenceDataSource {
  @override
  _i2.Future<_i6.CategoryPreferencesData> fetchCategoriesWithPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoriesWithPreferences, []),
            returnValue: _i2.Future<_i6.CategoryPreferencesData>.value(
              _FakeCategoryPreferencesData_7(
                this,
                Invocation.method(#fetchCategoriesWithPreferences, []),
              ),
            ),
            returnValueForMissingStub:
                _i2.Future<_i6.CategoryPreferencesData>.value(
                  _FakeCategoryPreferencesData_7(
                    this,
                    Invocation.method(#fetchCategoriesWithPreferences, []),
                  ),
                ),
          )
          as _i2.Future<_i6.CategoryPreferencesData>);

  @override
  _i2.Future<_i6.CategoryPreferencesData> saveCategoryPreferences({
    required List<int>? categoryIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCategoryPreferences, [], {
              #categoryIds: categoryIds,
            }),
            returnValue: _i2.Future<_i6.CategoryPreferencesData>.value(
              _FakeCategoryPreferencesData_7(
                this,
                Invocation.method(#saveCategoryPreferences, [], {
                  #categoryIds: categoryIds,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i2.Future<_i6.CategoryPreferencesData>.value(
                  _FakeCategoryPreferencesData_7(
                    this,
                    Invocation.method(#saveCategoryPreferences, [], {
                      #categoryIds: categoryIds,
                    }),
                  ),
                ),
          )
          as _i2.Future<_i6.CategoryPreferencesData>);
}
